### ISSUE TITLE
Improve the link between action version and docker image version

### ISSUE THREAD

**Issue by ewjoachim** [ewjoachim/python-coverage-comment-action#38]
## Build Dockerfile seemlessly

It would be nice if we could read a local variable (DEBUG or BUILD_FROM_DOCKERFILE), (an action parameter that could be set  set as repository variable or hardcoded in the workflow), that would switch from pulling the image to building it from the Dockerfile.

I'm sure we're not the first ones doing that, so maybe we can reuse something.

## Use correct version

I believe that, as of today, using a release tag of the version still ends up using the latest docker version, so it's probably quite useless.

**Comment by kieferro** [comment]
> It would be nice if we could read a local variable that would switch from pulling the image to building it from the Dockerfile.

I have tried a bit and here are my results so far: We have two options: Either we use (as currently) `using: docker` or `using: composite`.
For a docker action [there seems to be no way](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-docker-container-actions) to include any conditioning like if queries. Also the value for `image:` seems to have to be hardcoded. Otherwise we could have just used an input parameter there too, which defaults to `docker://ewjoachim/python-coverage-comment-action:latest` and can be changed to `Dockerfile`. However, this does not work in my tests.
If we use a composite action, we can use [if-queries](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsstepsif) and also Docker images with environment can be used by simply specifying published Docker image in `uses:`. However, this does not work with the local Dockerfile.

That's why I thought we could just build and run the Docker image locally for the debug case:
```yaml
runs:
  using: "composite"
  steps:
    - name: Run latest published version
      if: ${{ inputs.BUILD_FROM_DOCKERFILE == 'false' }}
      uses: docker://ewjoachim/python-coverage-comment-action:latest
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GITHUB_PR_RUN_ID: ${ inputs.GITHUB_PR_RUN_ID }}
        COMMENT_TEMPLATE: ${ inputs.COMMENT_TEMPLATE }}
        COVERAGE_DATA_BRANCH: ${ inputs.COVERAGE_DATA_BRANCH }}
        COMMENT_ARTIFACT_NAME: ${ inputs.COMMENT_ARTIFACT_NAME }}
        COMMENT_FILENAME: ${ inputs.COMMENT_FILENAME }}
        MINIMUM_GREEN: ${ inputs.MINIMUM_GREEN }}
        MINIMUM_ORANGE: ${ inputs.MINIMUM_ORANGE }}
        MERGE_COVERAGE_FILES: ${ inputs.MERGE_COVERAGE_FILES }}
        VERBOSE: ${ inputs.VERBOSE }}
        
    - name: Run Dockerfile
      if: ${ inputs.BUILD_FROM_DOCKERFILE == 'true' }}
      run: |
        docker build --file Dockerfile --tag coverage-comment-action .
        docker run coverage-comment-action
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GITHUB_PR_RUN_ID: ${ inputs.GITHUB_PR_RUN_ID }}
        COMMENT_TEMPLATE: ${ inputs.COMMENT_TEMPLATE }}
        COVERAGE_DATA_BRANCH: ${ inputs.COVERAGE_DATA_BRANCH }}
        COMMENT_ARTIFACT_NAME: ${ inputs.COMMENT_ARTIFACT_NAME }}
        COMMENT_FILENAME: ${ inputs.COMMENT_FILENAME }}
        MINIMUM_GREEN: ${ inputs.MINIMUM_GREEN }}
        MINIMUM_ORANGE: ${ inputs.MINIMUM_ORANGE }}
        MERGE_COVERAGE_FILES: ${ inputs.MERGE_COVERAGE_FILES }}
        VERBOSE: ${ inputs.VERBOSE }}
```
However, the problem here is that the whole thing is then not executed in the action repo, but in the repo in which the action is run. And logically, the files for building the Docker image do not exist there.
So there seems to be a catch for all possibilities I found so far. Do you have any ideas how to fix one of them?
